# Generated by Django 5.2.4 on 2025-07-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_question_topic_alter_question_correct_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4')], max_length=10, verbose_name='Correct Option'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(max_length=200, verbose_name='Option 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(max_length=200, verbose_name='Option 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(max_length=200, verbose_name='Option 3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(max_length=200, verbose_name='Option 4'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('database_management', 'Database Management'), ('system_analysis', 'System Analysis and Design'), ('artificial_intelligence', 'Artificial Intelligence'), ('technopreneurship', 'Technopreneurship'), ('compiler_design', 'Compiler Design and Construction')], max_length=50, verbose_name='Topic'),
        ),
    ]
